name: BodyBuildingCooperative
favicon: null
layout_spectrum: 0.24553
typography_spectrum: 0.32183
title: Power in Numbers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060b07'
    - '#fefefe'
    - '#b5cde2'
    - '#546c32'
    - '#9e9590'
  brandStrength: 0.4375
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
