name: BodyBuildingCooperative
favicon: null
layout_spectrum: 1
typography_spectrum: 0.32183
title: Power in Numbers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#050503'
    - '#bcc5ce'
    - '#757482'
    - '#46b28d'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
