name: BodyBuildingCooperative
favicon: null
layout_spectrum: 0.50417
typography_spectrum: 0.32183
title: Power in Numbers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e74c3c'
    - '#ecf0f1'
    - '#2980b9'
    - '#3498db'
    - '#2c3e50'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
